name: CI

on: [push]

env:
  POETRY_VERSION: 1.2.0
  POETRY_URL: https://install.python-poetry.org
  REDIS_VERSION: 7.0.5
  REDIS_PORT: 6379
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ENABLE_PUBLIC_ACCESS: 1
  HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

jobs:
  pyright:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Poetry cache depends on OS, Python version and Poetry version.
      - name: Cache Poetry cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}

      # virtualenv cache depends on OS, Python version and `poetry.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run Pyright
        run: poetry run pyright
  pytest-fast:
    runs-on: ubuntu-latest
    timeout-minutes: 10
#    needs: pyright
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Poetry cache depends on OS, Python version and Poetry version.
      - name: Cache Poetry cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ matrix.python-version }}-${{ env.POETRY_VERSION }}

      # virtualenv cache depends on OS, Python version and `poetry.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --with test

      - name: Start Redis
        run: docker run -d -p ${{ env.REDIS_PORT }}:${{ env.REDIS_PORT }} redis:${{ env.REDIS_VERSION }} redis-server 
             --requirepass ${{ env.REDIS_PASSWORD }}
             --port ${{ env.REDIS_PORT }}

      - name: Run Tests
        run: poetry run pytest
  end-to-end:
    runs-on: ubuntu-latest
    timeout-minutes: 15
#    needs: pyright
    steps:
      - uses: actions/checkout@v2

      - name: E2E docker-compose tests
        run: make tests-up
